### ISSUE TITLE
make lpc an optional external format like any other

### ISSUE THREAD

**Issue by janstary** [janstary/sox#12]
Do we need to carry our own copy of that implementation in the lpc10/ subdir?
Either implement lpc like any other format, or make it an optional external dependency,
(if a separate library exists, like for gsm or ogg or any format SoX itself does not implement).

**Comment by janstary** [comment]
Right, lpc10/ needs to be brought out of 1996 and dealt with separately.

```
#if defined(SHRT_MAX) && defined(SHRT_MIN) && SHRT_MAX==32767 && SHRT_MIN==(-32768)
typedef short INT16;
#elif defined(INT_MAX) && defined(INT_MIN) && INT_MAX==32767 && INT_MIN==(-32768)
typedef int INT16;
#else
#error Unable to determine an appropriate definition for INT16.
#endif
```

**Comment by janstary** [comment]
```
Revision 1.1  2007/04/16 21:57:22  rrt
LPC-10 support, documentation still to come; I wanted to land the code
before 14.0.0 went into test, and I'll be busy tomorrow.

Not highly tested either, but it's just a format, doesn't interfere
with anything else, and I'll get on that case before we go stable.
```

**Comment by janstary** [comment]
Started here: https://github.com/janstary/lpc

**Comment by martinwguy** [comment]
Looks like it was never finished, In fact man sox | grep lpc or redictiv produce nothing and `grep nuke *` in lpc10/ says:
README:I've made up a Unix makefile for the programs nuke and unnuke, called
README:nuke - compressing one audio stream
README:nuke2 - compressing two audio streams, alternating one frame from each
README:unnuke - decompressing one audio stream
README:unnuke2 - decompressing two audio streams, alternating one frame from each
but `find . -name *nuke*` produces nothing.

The README is a fascinating read, the code is a master work of DSP but it looks like SoX doesn't use it in any way, other than by linking its routines into libsox. If so, I'll resurrect it separately by writing nuke and unnuke and we can have two more external decoders... or as -llpc10

**Comment by janstary** [comment]
Removed the `lpc10/` subdir and added lpc as an optional format in 2f479f0379bab246bbb22c7bd78479aec0e48fad, a50b2c56bac94200e3375475a29f82fce1287260 and 7ba32b729efe378377cd328b7370737002609409.

**Comment by janstary** [comment]
What was the `lpc10/` subdir is _not_ Andy's code, apparently someone bundled thta into SoX itself a long time ago,
without those examples and without those makefiles.

But it definitely _was_ finished, and it works. I have already separated a standalone library
in https://github.com/janstary/lpc , starting form what was `lpc10/` in SoX (not having any better version).
That's what I've been testing against.

```
sox -r 8k -b 16 -c 1 -n file.wav synth 2 sin 440 gain -3
sox file.wav file.lpc
play file.lpc
```

Works just fine, even if the sound quality is pretty horrible.
That is to say, SoX does have a lpc encoder and decoder.

**Comment by janstary** [comment]
The lpc code seems to pre-date `stdint.h`, I had to remove mentions of `INT32` for example.
What _is_ `INT32` you ask? Well, that depends on what your machine is:

```
#if defined(INT_MAX) && defined(INT_MIN) && INT_MAX==2147483647 && INT_MIN==(-2147483647-1)
typedef int INT32;
#elif defined(LONG_MAX) && defined(LONG_MIN) && LONG_MAX==2147483647 && LONG_MIN==(-2147483647-1)
typedef long INT32;
#else
#error Unable to determine an appropriate definition for INT32.
#endif
```

It might be an int, and it might be a long; let's call it `INT32`.
Yes, the current master branch of SoX contains code like that.

**Comment by janstary** [comment]
Andy's README and the comments in the individual files are indeed a good lesson of DSP.
Apparently, he is still active: https://github.com/jafingerhut
